"use client";
import Head from "next/head";
import Course from "@/components/Course";




export default function Page() {

    return (
        <div>
            <Head>
                <title>mathquill4quill Nextjs Demo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Course />
            </main>

        </div>
    );
}